# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/achiever/Documents/code_file/python_file/face_new/ui/recong.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1067, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_Image = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget_Image.sizePolicy().hasHeightForWidth())
        self.widget_Image.setSizePolicy(sizePolicy)
        self.widget_Image.setObjectName("widget_Image")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_Image)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_image = QtWidgets.QLabel(self.widget_Image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.horizontalLayout.addWidget(self.label_image)
        self.label_down = QtWidgets.QLabel(self.widget_Image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_down.sizePolicy().hasHeightForWidth())
        self.label_down.setSizePolicy(sizePolicy)
        self.label_down.setText("")
        self.label_down.setObjectName("label_down")
        self.horizontalLayout.addWidget(self.label_down)
        self.verticalLayout_2.addWidget(self.widget_Image)
        self.widget_button = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_button.sizePolicy().hasHeightForWidth())
        self.widget_button.setSizePolicy(sizePolicy)
        self.widget_button.setObjectName("widget_button")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_button)
        self.gridLayout.setObjectName("gridLayout")
        self.button_file = QtWidgets.QPushButton(self.widget_button)
        self.button_file.setObjectName("button_file")
        self.gridLayout.addWidget(self.button_file, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(129, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 9, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(129, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.button_recognition = QtWidgets.QPushButton(self.widget_button)
        self.button_recognition.setObjectName("button_recognition")
        self.gridLayout.addWidget(self.button_recognition, 0, 6, 1, 1)
        self.button_back = QtWidgets.QPushButton(self.widget_button)
        self.button_back.setObjectName("button_back")
        self.gridLayout.addWidget(self.button_back, 0, 8, 1, 1)
        self.button_camera = QtWidgets.QPushButton(self.widget_button)
        self.button_camera.setObjectName("button_camera")
        self.gridLayout.addWidget(self.button_camera, 0, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_file.setText(_translate("Form", "从文件读取"))
        self.button_recognition.setText(_translate("Form", "识别"))
        self.button_back.setText(_translate("Form", "返回"))
        self.button_camera.setText(_translate("Form", "打开摄像头"))
